version: 0.0
os: linux

files:
        - source: /
          destination: /tmp

permissions:
        - object: /tmp/scripts/*.sh
          owner: root
          group: root
          mode: 777
          type:
            - file

hooks:
        ApplicationStop: 
                - location: scripts/stop_server.sh
                  timeout: 5
                  runas: root
        ApplicationStart:
                - location: scripts/start_server.sh
                  timeout: 5 
                  runas: root
