version: 0.0
os: linux

files:
  - source: /
    destination: /tmp

hooks:
        ApplicationStop: 
                - location: scripts/stop_server.sh
                  timeout: 5
                  runas: root
        ApplicationStart:
                - location: scripts/start_server.sh
                  timeout: 30
                  runas: root
