version: 0.0
os: linux

files:
        - source: /
          destination: /tmp

permissions:
        - object: /tmp/*.sh
          owner: root
          group: root
          mode: 777
          type:
            - file

hooks:
        BeforeInstall:
        Install:
                - location: install.sh
                - timeout: 60
                - runas: root
        ApplicationStart:
                - location: start.sh
                  timeout: 30 
                  runas: root
