version: 0.0
os: linux

files:
        - source: /
          destination: /tmp

permissions:
        - object: *.sh
          owner: root
          group: root
          mode: 777
          type:
            - file

hooks:
        ApplicationStart:
                - location: install.sh
                  timeout: 30 
                  runas: root
